export default {
    TOAST_RECEIVE: 'TOAST_RECEIVE',
    TOAST_REQUEST: 'TOAST_REQUEST',
    TOAST_FAILURE: 'TOAST_FAILURE',
    TOAST_INITIAL: 'TOAST_INITIAL',
    TOAST_ACCEPT: 'TOAST_ACCEPT',
  }
  